# Generated by Django 5.2.7 on 2025-10-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='owner',
            new_name='user',
        ),
    ]
