# Generated by Django 5.2.7 on 2025-10-10 21:08

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_rename_owner_brand_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-updated_at', 'name']},
        ),
        migrations.AlterModelOptions(
            name='brandsample',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the brand, its values, or key characteristics', null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='brandsample',
            name='chunk_index',
            field=models.PositiveIntegerField(default=0, help_text='Index of this chunk within the original document (0 for single chunk)'),
        ),
        migrations.AddField(
            model_name='brandsample',
            name='file_ref',
            field=models.CharField(blank=True, help_text='Reference to the original uploaded file', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brandsample',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Size of the original file in bytes', null=True),
        ),
        migrations.AddField(
            model_name='brandsample',
            name='file_type',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF Document'), ('docx', 'Word Document'), ('txt', 'Text File'), ('md', 'Markdown File')], help_text='Type of the original file this sample was extracted from', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='brandsample',
            name='total_chunks',
            field=models.PositiveIntegerField(default=1, help_text='Total number of chunks the original document was split into'),
        ),
        migrations.AddField(
            model_name='brandsample',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='brandsample',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Vector embedding for semantic search', null=True),
        ),
        migrations.AlterField(
            model_name='brandsample',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='brandsample',
            index=models.Index(fields=['brand', '-created_at'], name='brands_bran_brand_i_89c6fb_idx'),
        ),
        migrations.AddIndex(
            model_name='brandsample',
            index=models.Index(fields=['file_ref'], name='brands_bran_file_re_960ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='brandsample',
            index=models.Index(fields=['file_type'], name='brands_bran_file_ty_a5e7f5_idx'),
        ),
    ]
