# Generated by Django 5.2.7 on 2026-01-02 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_alter_brand_options_alter_brandsample_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandVoiceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User-provided name for this voice analysis', max_length=100)),
                ('confidence_score', models.FloatField(default=0.7, help_text='Analysis confidence (0-1)')),
                ('voice_analysis', models.JSONField(default=dict, help_text='Tone, style, personality traits, communication patterns, content themes')),
                ('emotional_indicators', models.JSONField(default=dict, help_text='Scores for selected emotional indicators')),
                ('brand_recommendations', models.JSONField(default=list, help_text='AI-generated brand recommendations')),
                ('samples_analyzed', models.IntegerField(default=0, help_text='Number of brand samples used in analysis')),
                ('total_text_length', models.IntegerField(default=0, help_text='Total character count of all samples')),
                ('use_for_audits', models.BooleanField(default=False, help_text='Use this voice analysis for post audits instead of profile analysis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, help_text='Associated brand if saved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_analyses', to='brands.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_voice_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'brand_voice_analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='brand_voice_user_id_545bf2_idx'), models.Index(fields=['use_for_audits'], name='brand_voice_use_for_3b5e1d_idx')],
            },
        ),
    ]
