# Generated by Django 5.2.7 on 2025-12-03 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0003_extensiontoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('confidence_score', models.FloatField(help_text='Analysis confidence (0-1)')),
                ('voice_analysis', models.JSONField(default=dict, help_text='Tone, style, content themes, communication patterns')),
                ('emotional_indicators', models.JSONField(default=dict, help_text='Scores for selected emotional indicators')),
                ('brand_recommendations', models.JSONField(default=list, help_text='AI-generated brand recommendations')),
                ('post_analyzed', models.IntegerField(default=0)),
                ('bio_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='profile_ana_user_id_4509d5_idx'), models.Index(fields=['platform', 'created_at'], name='profile_ana_platfor_08b93a_idx'), models.Index(fields=['handle'], name='profile_ana_handle_5188c9_idx')],
            },
        ),
    ]
