# Generated by Django 5.2.7 on 2025-12-22 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], max_length=10)),
                ('mission_type', models.CharField(choices=[('discrete', 'Discrete'), ('progress', 'Progress')], default='discrete', max_length=10)),
                ('target_count', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_manual', models.BooleanField(default=False, help_text='Requires manual completion confirmation')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'onboarding_missions',
                'ordering': ['tier', 'order'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checklist_collapsed', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onboarding_state',
            },
        ),
        migrations.CreateModel(
            name='UserMissionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_count', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='onboarding.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_mission_progress',
                'indexes': [models.Index(fields=['user', 'is_completed'], name='user_missio_user_id_7a3aba_idx')],
                'unique_together': {('user', 'mission')},
            },
        ),
    ]
