# Generated by Django 5.2.7 on 2025-11-25 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0003_alter_brand_options_alter_brandsample_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The content that was audited')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('other', 'Other')], help_text='platform chosen from platform choices', max_length=20)),
                ('score', models.FloatField(help_text='Overall brand voice alignment score (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.JSONField(default=dict, help_text='Additional context (has_media, is_thread, etc)')),
                ('content_embedding', models.JSONField(blank=True, help_text='Vector embedding of audited content', null=True)),
                ('brand', models.ForeignKey(help_text='Brand profile used for this audit', on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='brands.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post Audit',
                'verbose_name_plural': 'Post Audits',
                'db_table': 'post_audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriftAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('message', models.TextField(help_text='Alert message describing the drift')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('threshold_breached', models.FloatField(help_text='The score threshold that triggered this alert')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_alerts', to='brands.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_alerts', to=settings.AUTH_USER_MODEL)),
                ('related_audits', models.ManyToManyField(related_name='drift_alerts', to='audits.postaudit')),
            ],
            options={
                'verbose_name': 'Drift Alert',
                'verbose_name_plural': 'Drift Alerts',
                'db_table': 'drift_alerts',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone_match', models.FloatField(help_text='How well tone matches brand voice')),
                ('vocabulary_consistency', models.FloatField(help_text='Vocabulary alignment score')),
                ('emotional_alignment', models.FloatField(help_text='Emotional tone alignment')),
                ('style_deviation', models.FloatField(help_text='Style consistency score')),
                ('deviations', models.JSONField(default=list, help_text='List of specific deviations found')),
                ('x_optimization', models.JSONField(blank=True, help_text='X/Twitter specific optimization tips', null=True)),
                ('ai_feedback', models.TextField(blank=True, help_text='AI-generated suggestions', null=True)),
                ('audit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='audits.postaudit')),
            ],
            options={
                'verbose_name': 'Audit Metrics',
                'verbose_name_plural': 'Audit Metrics',
                'db_table': 'audit_metrics',
            },
        ),
        migrations.CreateModel(
            name='AuditUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('audit_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_usage',
                'indexes': [models.Index(fields=['user', 'date'], name='audit_usage_user_id_dca2b8_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='postaudit',
            index=models.Index(fields=['user', '-created_at'], name='post_audits_user_id_b53f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='postaudit',
            index=models.Index(fields=['brand', '-created_at'], name='post_audits_brand_i_cbc70b_idx'),
        ),
        migrations.AddIndex(
            model_name='postaudit',
            index=models.Index(fields=['platform', '-created_at'], name='post_audits_platfor_9f669c_idx'),
        ),
        migrations.AddIndex(
            model_name='postaudit',
            index=models.Index(fields=['score'], name='post_audits_score_4b0b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='driftalert',
            index=models.Index(fields=['user', '-detected_at'], name='drift_alert_user_id_6c7e09_idx'),
        ),
        migrations.AddIndex(
            model_name='driftalert',
            index=models.Index(fields=['brand', '-detected_at'], name='drift_alert_brand_i_bb076b_idx'),
        ),
        migrations.AddIndex(
            model_name='driftalert',
            index=models.Index(fields=['acknowledged'], name='drift_alert_acknowl_956321_idx'),
        ),
    ]
