# Generated by Django 5.2.7 on 2025-11-26 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditusage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postaudit',
            name='score',
            field=models.FloatField(blank=True, default=0.0, help_text='Overall brand voice alignment score (0-100)', null=True),
        ),
    ]
