# Generated by Django 5.2.7 on 2025-11-26 17:04

import audits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_alter_auditusage_date_alter_postaudit_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditusage',
            name='date',
            field=models.DateField(default=audits.models.get_current_date),
        ),
    ]
