# Generated by Django 5.2.7 on 2025-12-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_alter_auditusage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditmetrics',
            name='metric_tips',
            field=models.JSONField(blank=True, default=dict, help_text='Improvement tips for each metric'),
        ),
    ]
