# Generated by Django 5.2.7 on 2026-01-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_auditmetrics_metric_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditmetrics',
            name='improvement_suggestions',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed improvement suggestions with actionable steps for each metric'),
        ),
    ]
